### ISSUE TITLE
Unable to deploy Contract which needs initial funding/value

### ISSUE THREAD

**Issue by Spejbl** [SuperblocksHQ/ethereum-studio#118]
## Summary

Consider the following Contract:
```
contract MyBank {
    constructor() public payable {
        require(msg.value == 42 ether, "42 ether initial funding required");
    }
}
```
Due to having `payable` constructor and `require` inside constructor that needs initial funding of `42` ether, it's not possible to deploy, because we don't have any `inputs` for such use case.

We could add a new input inside Contract configuration modal where user can add initial funds for constructor.

## Additional context
Sample project
[![Edit Project](https://studio.ethereum.org/static/img/open-studio.svg)](https://studio.ethereum.org/5dc52d8326b473001233c612?openFile=contracts/MyBank.sol)

**Comment by filippsen** [comment]
@Spejbl this is the same field as _Value_ when performing other transactions (same as _Interact_). It makes sense to add it to _Configure_ as it is contract-specific context. Adding to _Preferences_ could cause confusion, making it look like a global setting instead.
