### ISSUE TITLE
Host introduction video on different platform?

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#130]
## Summary
@ChrisChinchilla - excellent work on the demo video you created! My only gripe - when I clicked the link from the "Welcome" screen, the page opened with this popup:

<img width="1440" alt="Image 2019-11-09 at 12 21 52 AM" src="https://user-images.githubusercontent.com/8097623/68606946-62db4780-0464-11ea-8971-d7c1e1e5500c.png">

Is there an alternative to Adobe that might give users less of a product pitch?

## Motivation

If possible I'd like to avoid creating any noise for the users - let them focus on Ethereum Studio.

## Describe alternatives you've considered

- YouTube? Ethereum channel?
- Vimeo?
- Others?

**Comment by samajammin** [comment]
@ChrisChinchilla - curious to hear your thoughts on this. Feel free to push back 😄

**Comment by ChrisChinchilla** [comment]
@samajammin This was just to share with you! I assumed you would host it somewhere else, but I had no idea where you do that sort of thing for the site :)

**Comment by samajammin** [comment]
Hmmm, I didn't add the video to this project. @jjmstark is this something you think we should add to the Ethereum YouTube channel? Who would we contact to make the happen? @Souptacular?

**Comment by samajammin** [comment]
My take - I think YouTube would be the best for improving the discoverability of the video (e.g. the potential for the video to get pulled into results pages when people search "ethereum studio"). YouTube itself has also become a dominant search engine.

**Comment by samajammin** [comment]
Does anyone object to hosting this video on [EF's channel on YouTube](https://www.youtube.com/channel/UCNOfzGXD_C9YMYmnefmPH0g)?

**Comment by ChrisChinchilla** [comment]
Not personally, though of course it would be nice to post to something less web2 ;)

I want to rerecord this soon anyway as a much better complete beginner video, but in the meantime, make sure any text gives people context to what it's about.

PS. I also have other videos in progress, so good to know we have a channel.

**Comment by samajammin** [comment]
@ChrisChinchilla any suggestions on alternatives that are "less web2"?

**Comment by ChrisChinchilla** [comment]
@samajammin err, no, I was rather hoping someone else would. So YouTube I guess
