### ISSUE TITLE
Update CryptoPizza to use latest version of OpenZeppelin Contracts

### ISSUE THREAD

**Issue by abcoathup** [SuperblocksHQ/ethereum-studio#165]
## Summary

Update CryptoPizza to use latest version of OpenZeppelin Contracts. 
Currently using OpenZeppelin Contracts 2.3 when latest version is OpenZeppelin Contracts 2.4 
Also currently using `openzeppelin-solidity` when package is now `@openzeppelin/contracts`

## Motivation
Latest version is OpenZeppelin Contracts 2.4 (https://forum.openzeppelin.com/t/openzeppelin-contracts-v2-4/1665) and includes Gas Station Network support.

`openzeppelin-solidity` is now `@openzeppelin/contracts` see the announcement from July
https://forum.openzeppelin.com/t/announcing-the-openzeppelin-sdk/1092

## Additional context
Ideally update imports to not need to refer to `node_modules`:
`import "@openzeppelin/contracts/...` rather than:
`import "../node_modules/openzeppelin-solidity/contracts/...`

*Disclosure: I am the Community Manager at OpenZeppelin*

**Comment by javier-tarazaga** [comment]
Hi @abcoathup ! 

Sure, lets aim to change this in the next release. In regards to the import part. We agreed back then with Martin and the guys to do it that way so in case you would like to move on into a different tool with the current codebase, you would not need to redo all the imports and you could pretty much copy/paste. Also if one day we would have a Github integration to sync with it, you could, in fact, work with a local project for a quick test.

**Comment by ChrisChinchilla** [comment]
We'll also need to update the templates when this is possible, or can I do both of those myself?

**Comment by javier-tarazaga** [comment]
@ChrisChinchilla, of course, you can :) Both the templates and import functionalities are checked into the repo
