### ISSUE TITLE
Update template READMEs based on user feedback

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#170]
## Summary

Add improvements to each template's README.

For each template README:
- [x] Explicitly call out contract file location in the README (e.g. "find the smart contract in /Files/contracts/HelloWorld.sol")
  - Same with the app.js for "The web app" section.
- [x] Move explanations about code into in-line comments (e.g. the current pragma explanation: ```"The first line, pragma solidity ^0.5.10 specifies that the source code is for a Solidity version greater than 0.5.10. Pragmas are common instructions for compilers about how to treat the source code (e.g., pragma once)."``` - this should be moved from the README into the .sol file as a comment above the pragma line. 
  - Same with the contract function explanations.
  - Same with the web app code explanations (some of the preview code in the README is actually different from the code in app.js. By keeping these explanations as in-line comments, we'll avoid the issue of having to update the code in multiple places when we make changes.)
- [x] Add a section that explains how to configure, compile & deploy in the README

## Motivation
We've received this feedback from multiple users & believe this will improve the developer experience.

## Describe alternatives you've considered
Onboarding tours of the application but that requires more work and/or paid 3rd party services. Updating the README of each template should be a quick win.
A clear and concise description of the alternative solutions you've considered.

**Comment by microftech65** [comment]
Updated reviewed approved Qbswhh@qdr22$README.md
[21_12_201909_34_02.pdf](https://github.com/SuperblocksHQ/ethereum-studio/files/3991994/21_12_201909_34_02.pdf)

**Comment by ChrisChinchilla** [comment]
Before I jump into the more complex ones, here's my attempt at the Hello World example, I think it's enough of a compromise?

https://github.com/SuperblocksHQ/ethereum-studio/pull/179

**Comment by frankfuttderBlogmitBanane** [comment]
böpbba
