### ISSUE TITLE
Configure dialog should not allow user to add variables that don't exist

### ISSUE THREAD

**Issue by ChrisChinchilla** [SuperblocksHQ/ethereum-studio#171]
## Summary

The configure popup for smart contracts feels confusing, as it allows you to add more variables not present in the constructor, which causes errors on deployment. Unless there's a reason for this I'm not seeing, I feel leaving it as auto detectable makes more sense.

## Motivation

For better user experience for beginners who may experiment and break their work.

## Describe alternatives you've considered

Leaving as is.

**Comment by javier-tarazaga** [comment]
Hi @ChrisChinchilla ! 

It seems like a good addition to simplifying that part. Also if we add an auto-compile/deploy feature with any code changes we would have always available the ABI to figure it out.
