### ISSUE TITLE
Simplify UX 

### ISSUE THREAD

**Issue by javier-tarazaga** [SuperblocksHQ/ethereum-studio#174]
## Summary

Make a few UI and UX changes in order to simplify even more the experience of using Ethereum studio. Some key points of the change are: 

1. Move away from the Intellij approach of having side panels and move towards a more simplified version of the UX leaning towards VSCode, Codesanbox, and Stackblitz (also users of these tools will feel comfortable straight away as follows the same patterns) 

2. Remove the network dropdown and allow only for now to interact with the browser EVM. This will indicate straight away that the network is the default and only network for now. In the case we would like to support more networks in the future, we could add a new section in the side menu for deployments.

3. Auto-compile and auto-deploy on every code change, following similar patterns as Codesanbox and Stackblitz. Also, this allows us to remove the awkward UX pattern of having configure/compile/deploy under each contract. 

4. The contract configuration has been moved to the side panel so it is easier to access. 

5. The selected account is rendered on the top right following a similar pattern as many sites already do. Also, we add the blockies (https://github.com/ethereum/blockies) to make it more obvious that it is a wallet. 

6. The former Preview (now Browser) and Transactions panels have been moved and are rendered as tabs, making in really obvious to see straight away. 

7. Removed all bottom indicators of Account Balance, gas price, etc. We could split those into the account dropdown and the settings menu. 

8. The help top action gets removed and gets merged into the wallet selector which will hold the list of the different available wallets and a support subsection. 

9. Also if we would need to add some more extensive tutorials to teach people about certain concepts, we could, in fact, add a new section in the left menu with a collection of them. 

## Motivation

From our first wave of interviews and user feedback, we have seen a recurrent pattern among many of them in which they asked to simplify the UI/UX of the tool in order to make it more obvious and simple to work with (also not overwhelming new users with a ton of options).

## Sketches

![Ethereum Studio - Explorer](https://user-images.githubusercontent.com/7814134/72166423-7a35a300-33c9-11ea-852f-596c3c3ddeeb.png)

![Ethereum Studio - Configure Contracts](https://user-images.githubusercontent.com/7814134/72166421-7a35a300-33c9-11ea-9b1b-c076342a494c.png)

![Ethereum Studio - Interact](https://user-images.githubusercontent.com/7814134/72166882-650d4400-33ca-11ea-92c2-82c9994c7513.png)

**Comment by samajammin** [comment]
Love these ideas overall!

Regarding
> 8. The help top action gets removed and gets merged into the wallet selector which will hold the list of the different available wallets and a support subsection.

I'm not sure I understand/agree with this. What is the "wallet selector"? Is that the same as account dropdown? To me those seem very separate things.

I think a help option is good for users to immediately see (though I agree it could be simplified). I recommend a few items in #178, please let me know what you think.

**Comment by javier-tarazaga** [comment]
In regards to point number 8. 

Yeap I meant Account selector (not wallet). The reason to move it to the account popup (ill create a sketch so we can have that as ref as well) is so as `Help` is an action you don't use often and only might be required in really specific moments, but tbh I don't I have a strong opinion about this. The sole idea of removing it is to simplify as much as possible the UI and remove anything from the main screen that you might not need often. 

In regards to the "wallet selector", as the idea behind there is that if we remove the possibility to have multiple networks, we will only have a single wallet with multiple accounts. That selector would be the one serving as a selector of which account is currently selected (as you would do in Metamask per example). In simple terms, the idea is to move the account selector to the right-hand side and modify a bit the popup.

**Comment by samajammin** [comment]
> `Help` is an action you don't use often and only might be required in really specific moments,

Do you have analytics on how often people have toggled this? That might help us make a decision.

While I appreciate your goal to keep slimming down the UI, I think it's important to keep a "help" option prevalent in the UI given that this is a tool for new developers to Ethereum & for most people it will probably be their first time using this tool. Nesting it under the account selector doesn't really make logical sense to me (though maybe I'm just missing something)?

I totally agree that having an account selector in general (a la Metamask) is useful, e.g. to validate that transferring tokens between different accounts works. I'm fine with the idea to move it to the right-hand side & modify it a bit.

**Comment by javier-tarazaga** [comment]
Unfortunately, there are no analytics around the help button action (which reminds me that we should open a new ticket to revisit all the analytics currently tracked) but what I mentioned, I don't have a strong opinion around this, so then lets's leave it as is until we have more info around it.

**Comment by javier-tarazaga** [comment]
Btw I had some spare time tonight and I already started the work myself. You can find the latest changes in the branch `new-ux`

**Comment by javier-tarazaga** [comment]
@lovrobiljeskovic I found a couple of issues to be fixed:

[ ] Browser Tab - We are still displaying the download button. This functionality should be removed as it does not make any sense when only working with the browser network.

[ ] Browser Tab - Atm there is no need to show the url box (we could simply hide it for now) until we have a way to actually serve each project through the given url

[ ] We need to re-add somewhere the `Export to Zip` button in the UI. I would follow the same principle as VSCode does and put it next to the panel name (remove the x and change it to the export icon). Here we could use the same icon for the `download button` we removed from the browser tab. 

[ ] Share dialog - The `Show transactions` and `Show Preview` don't have any effect any longer. Also, Preview is now called Browser. 




[ ]

**Comment by javier-tarazaga** [comment]
@lovrobiljeskovic I had some time tonight and I helped out a little bit with this. The latest changes for the next wave of refinements are in the branch `more-ui-refinements`

**Comment by samajammin** [comment]
Just checked out https://studio-staging.ethereum.org/ - great progress folks, nice work!

Came here to report the issues @javier-tarazaga already covered in https://github.com/SuperblocksHQ/ethereum-studio/issues/174#issuecomment-576421459 😄. The only thing I'd add is I think we can also remove the "Settings" button on the "Browser" tab. Disabling the Web3 Provider seems like a relatively advanced feature that I think we can do without for now:

![Image 2020-01-21 at 2 34 19 PM](https://user-images.githubusercontent.com/8097623/72849295-3cebd380-3c5b-11ea-889b-261e9265e229.png)

My sense is that we could do without that entire bar (refresh button, URL box, download button & settings button). Is there any reason you folks think we should keep any of these features (e.g. is there any reason someone would need to refresh the browser)?

Thanks again!

**Comment by lovrobiljeskovic** [comment]
@javier-tarazaga made a pull request for the last change: #185 
Regarding the changes proposed by @samajammin : I think both ''Settings'' and refresh button could be removed, what do you think?

**Comment by javier-tarazaga** [comment]
@samajammin good to hear! There is 2 main reason for having that bar: 

- In case, for what ever reason, you want to force a page refresh. 

- Eventually would be great to have the feature like codesanbox/stackblitz/etc do have in which the tool automatically deploys the FE of the dApp to a CDN and makes it available to the user. There a few reasons why is really handy being the basic one the fact that you could have the code in one screen and the webpage in another. Also, this means that you can share your dapp creation with anyone by simply sharing the URL of the webpage itself. (https://d6o5n.csb.app) as an example. 

Well, in fact thinking about it, MM does not inject the web3 object any longer, therefore it is the developer's responsibility to bring whichever web3 library desires to use to communicate with their provider (or any other for that matter). So yes, let's remove it for now

**Comment by samajammin** [comment]
Thanks for the explanation @javier-tarazaga.

> In case, for what ever reason, you want to force a page refresh.

But is there ever a need to refresh?

> Eventually would be great to have the feature like codesanbox/stackblitz/etc do have in which the tool automatically deploys the FE of the dApp to a CDN and makes it available to the user.

I agree this would be great but until we have that feature, I say we remove the URL bar.

**Comment by javier-tarazaga** [comment]
@samajammin now I do remembrer. The reason had to do that atm we only do refresh the page automatically in this cases: 

case deployerActions.DEPLOY_SUCCESS:
case explorerActions.INIT_EXPLORER_SUCCESS:
case projectsActions.SET_ENVIRONMENT_SUCCESS:
case previewActions.REFRESH_CONTENT:

So in order to accommodate that I added some changes to auto-refresh the page when saving either any js/html/css file. 

I would still argue that I would keep that bar there and maybe even add back the url box part. At the end of the day that is used to represent a browser window. If for what ever reason the auto render function fails, you always have the backup to refresh the page.

**Comment by samajammin** [comment]
Ok, I have no major issue with that. As long as we remove the "download" & "settings" buttons.

**Comment by javier-tarazaga** [comment]
Oks great. Yeap I do agree, and those are already removed.
