### ISSUE TITLE
Auto-expand the file tree

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#175]
## Summary

Let's update the default file tree behavior to be fully expanded.

#### Current default display

![Image 2020-01-11 at 11 23 48 AM](https://user-images.githubusercontent.com/8097623/72209591-e9140a00-3464-11ea-8170-d30a4f1ec128.png)

#### Desired default display

![Image 2020-01-11 at 11 24 02 AM](https://user-images.githubusercontent.com/8097623/72209586-e5808300-3464-11ea-99b2-7254d74af89f.png)

## Motivation

Based on user feedback, this would help users locate key features such as `Configure`, `Compile` & `Deploy`, which are currently nested under the contract file.

## Describe alternatives you've considered
- Calling out the location of specific files in the READMES (Implemented in #172)
- Making the `Configure`, `Compile` & `Deploy` more prevalent

**Comment by javier-tarazaga** [comment]
Fixed in #182
