### ISSUE TITLE
Remove network dropdown

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#177]
## Summary

Remove the network dropdown from the UI:

![Image 2020-01-11 at 11 35 54 AM](https://user-images.githubusercontent.com/8097623/72209753-b5d27a80-3466-11ea-92de-fe576114d936.png)

## Motivation

We've agreed on the product decision to remove network options for the time being. We've gotten user feedback & support questions that the dropdown is confusing. It gives the impression that the option exists but it only has one option. It creates suspicion that there's a bug.

This will also help to simplify the UI & UX (#174), which users have reported has an overwhelming amount of features.

## Describe alternatives you've considered
- Adding more network options
- Keeping UI as it currently is

## Additional context
None

**Comment by nglglhtr** [comment]
@samajammin, just curious, so there isn't an option to deploy on networks other than the in-browser blockchain?

**Comment by javier-tarazaga** [comment]
This will be fixed with #174

**Comment by javier-tarazaga** [comment]
Fixed in #174
