### ISSUE TITLE
Consolidate troubleshooting channels

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#178]
## Summary

Brainstorm & implement a simpler support system for Studio by consolidating troubleshooting channels.

Currently we have several support related options:
- Help center (top right dropdown): https://help.superblocks.com/en/
- Ask a question (top right dropdown): https://discuss.superblocks.com/c/ethereum-studio
- ETH docs help (top right dropdown): https://gitter.im/ethereum/documentation

Let's remove the "Help center" link, since the "Guide to Ethereum Studio" links to the same Telecom support resource.

Let's pick one support channel to direct people to (e.g. [the Discourse](https://discuss.superblocks.com/c/ethereum-studio)) for questions & issues. Then remove references to the other option (e.g. [the documentation Gitter](https://gitter.im/ethereum/documentation)).

Within the ["Guide to Ethereum Studio"](https://help.superblocks.com/en/collections/1865071-ethereum-studio), let's add an article "Where can I get help?" that provides an additional link to our chosen support channel.

## Motivation

From our first wave of interviews and user feedback, we have seen a recurrent pattern among many of them in which they asked to simplify the UI/UX of the tool in order to make it more obvious and simple to work with (also not overwhelming new users with a ton of options).

## Describe alternatives you've considered
Keep as is

## Additional context
None

**Comment by samajammin** [comment]
@ChrisChinchilla curious to get your input on this.

**Comment by javier-tarazaga** [comment]
Btw I am not sure Discord would be the best place to direct all the main support questions and the reason is mainly that chats are not indexable, therefore whatever anyone asks, simply gets forgotten and no one can't actually search for it (as we all do when we have an issue). 

That was the main motivation to have a discussion forum in the first place. We consider in the past to have Q/A questions in https://ethereum.stackexchange.com/ which might be a good candidate as well imo.

**Comment by javier-tarazaga** [comment]
Also, the Help Center is the actual documentation of the tool with articles describing how to do certain things in the tool, so I would also leave that one as otherwise there is no official documentation of the tool itself and the only support available is by either chat/qa/forum

**Comment by samajammin** [comment]
> Btw I am not sure Discord would be the best place to direct all the main support questions and the reason is mainly that chats are not indexable, therefore whatever anyone asks, simply gets forgotten and no one can't actually search for it (as we all do when we have an issue).

Agreed, that's why I suggested [your Discourse](https://discuss.superblocks.com/c/ethereum-studio) (not Discord).

> Also, the Help Center is the actual documentation of the tool with articles describing how to do certain things in the tool, so I would also leave that one as otherwise there is no official documentation of the tool itself and the only support available is by either chat/qa/forum

Also agree, I just don't think 2 links ("Help center" & "Guide to Ethereum Studio") are required.

**Comment by javier-tarazaga** [comment]
Oks cool. Let then leave it like that. I'll assign this issue as well so get it done next week.

**Comment by javier-tarazaga** [comment]
The page in the help center for studio is published. 

https://help.superblocks.com/en/articles/3641749-where-can-i-get-help

**Comment by javier-tarazaga** [comment]
This is fixed by #180
