### ISSUE TITLE
Undesired position of the context menu when Right-clicking

### ISSUE THREAD

**Issue by hideckies** [SuperblocksHQ/ethereum-studio#200]
## Environment/Browser
Google Chrome version  80.0.3987.106
Windows 10

## Description
I want to select _`Import File`_ on context menu Right-clicking, but the context menu is too left of expected position. Because of that, it cannot be selected.

## Steps to reproduce
1. Move the cursor to the range where _files hierarchy_ is.
2. Right click

## Actual result
![eth_studio_screen](https://user-images.githubusercontent.com/52585124/74671454-8db90280-51ee-11ea-8833-28a9a757f4f1.png)

**Comment by hideckies** [comment]
Displayed correctly when expanding the range of the  _EXPLORER (files hierarchy)_ .

### **Before**
![screen1](https://user-images.githubusercontent.com/52585124/74676934-87308800-51fa-11ea-960f-86827bd3cf96.png)

### **After**
![screen2](https://user-images.githubusercontent.com/52585124/74676943-8c8dd280-51fa-11ea-8d9a-b793e1eb8d54.png)

**Comment by Spejbl** [comment]
Hey @hideckies! Thank you for filling out the issue, I've created a PR for this fix in #201 so please take a look if it resolves it. :)

**Comment by hideckies** [comment]
@Spejbl 
Thanks for the prompt response😃
