### ISSUE TITLE
Add "Next steps" section to each project template README

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#203]
## Summary

Since the goal of Ethereum Studio is to provide a brief introduction to building on Ethereum & serve as a stepping stone to further tools / learning resources, it'd be great to add a list of suggestions to people who have finished the README, e.g. CryptoZombies to learn Solidity syntax or Remix to dive deeper into smart contract development.

## Motivation

The goal here is to provide continued learning to users after they've explored Ethereum Studio.

## Describe alternatives you've considered

We'll also plan to add expanded descriptions of tools on the ethereum.org/build page but think it makes sense to include resources in this context as well.

**Comment by ChrisChinchilla** [comment]
Good call, I have a few things in mind like Grid etc. I'll take this one.
