### ISSUE TITLE
Don't display form inputs in UI unless contract is deployed

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#207]
## Summary

It's confusing to create a project, e.g. the Coin template & to try to interact with the form inputs in the UI. They don't do anything & there's no error message explaining that the user must first compile & deploy the contract. This could lead to confusion & frustration.

## Motivation

Improve UX.

## Describe alternatives you've considered

- Show an error message if no contract has been deployed & user attempts to submit values

**Comment by nathan-lapinski** [comment]
@samajammin Is this issue related to #228 ? I've opened up a PR for 228 that hopefully addresses the issues that you've mentioned here as well.

**Comment by samajammin** [comment]
🤔 ya this looks to be a duplicate. I'll close this out in favor of #228.
