### ISSUE TITLE
Automatically open console on first console message

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#209]
## Summary

The [green alert circle](https://share.getcloudapp.com/4gum056A) is nice but let's pop the console tab open when the first output appears to make this feature even more obvious.

## Motivation
The goal here is to quickly demonstrate the console's functionality & the interactiveness of the app's tabs.

## Describe alternatives you've considered
None

## Additional context
None

**Comment by Spejbl** [comment]
Resolved in #216
