### ISSUE TITLE
Auto compile contracts on save

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#211]
## Summary

- [x] Every time a contract file is saved, attempt to compile it
- [x] Remove all ["compile" UI buttons](https://share.getcloudapp.com/JruWxE8D) 
- [x] Remove all "compile" instructions from the READMEs
- [x] For each project template, pre-compile the contract so the user can immediately deploy

## Motivation
Simpler UI & less repetitive actions required by the user

## Describe alternatives you've considered
None

## Additional context
For the most part, this is already done. We just need to ensure this takes place on every save action. @javier-tarazaga mentioned one event listener we may need to account for that we're not currently.

**Comment by javier-tarazaga** [comment]
@samajammin I think we can close this issue. If anything is required here, let's create a new one.
