### ISSUE TITLE
After Hello World, how to get to the next project?

### ISSUE THREAD

**Issue by ethers** [SuperblocksHQ/ethereum-studio#229]
At startup the user sees a list of projects, starting with Hello World.

After Hello World, it is not clear how to get to the next project?  The studio should make this easy and clear.

**Comment by javier-tarazaga** [comment]
Good point! 

We will be working in a little guide when starting the tool to exactly show you how to do that afterward. It is really easy but might not be obvious at first sight.

**Comment by samajammin** [comment]
Solved in #235
