### ISSUE TITLE
Bug in studio prevents compilation

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#240]
Not certain if this is still an issue but recording here:
https://discuss.superblocks.com/t/bug-in-studio-prevents-compilation/64

**Comment by lovrobiljeskovic** [comment]
@samajammin Hey Sam, I was investigating this today, and I believe I fixed this with this commit https://github.com/SuperblocksHQ/ethereum-studio/commit/2f9d7e2fda70258f17504f12f858095cde722f9c
Let me know if you manage to reproduce it but I think this one can be closed

**Comment by samajammin** [comment]
Nice! Ya that commit indeed looks to be the fix. I wasn't able to repro the bug.

Closing this out. Thanks!
