### ISSUE TITLE
Ii

### ISSUE THREAD

**Issue by walid161hatam** [SuperblocksHQ/ethereum-studio#257]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/ethereum-studio.

**Comment by walid161hatam** [comment]
تبدیل رمزبه سکه

**Comment by javier-tarazaga** [comment]
Hi @walid161hatam, 

Closing this issue for now. If you experience a bug or would like to have a new feature, please create a new issue and provide a good description. 

Thanks!
