### ISSUE TITLE
Bug: Coin "mint" function hangs if not triggered by owner

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#262]
## Environment/Browser
Brave v 1.9.72

## Description
When trying to mint coins from an account other than the account owner, the transaction hangs indefinitely.

## Steps to reproduce
1. Create Coin project
2. Deploy contract
3. Add new account
4. Select new account
5. Try to mint tokens

## Expected result
- We should display an error message (ideally the revert message) in the browser UI
- The transaction should fail (with the revert message) in the transaction panel
- We should log an error to the console

## Actual result
Nothing happens in the UI & the transaction just hangs:
![Image 2020-06-09 at 1 57 44 PM](https://user-images.githubusercontent.com/8097623/84199276-b8f38600-aa59-11ea-9435-5bb625d524fa.png)

## Reproducible
100%

**Comment by lovrobiljeskovic** [comment]
Hey @samajammin I created a new PR: https://github.com/SuperblocksHQ/ethereum-studio/pull/264, mind checking it out and seeing if all is good? It should fix this issue as well as #260
