### ISSUE TITLE
Update README instructions

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#27]
## Summary

The "Issues" & "Contributing" sections are both outdated. They lead to dead wiki links:
https://github.com/SuperblocksHQ/ethereum-studio/wiki/Submitting-Bugs-and-Suggestions
https://github.com/SuperblocksHQ/ethereum-studio/wiki/How-to-Contribute

I'm also not sure if the "Quick start" instructions are up to date. See https://github.com/SuperblocksHQ/ethereum-studio/issues/25

## Motivation

Before public Ethereum Studio launch we should provide clear instructions for folks to contribute.

**Comment by javier-tarazaga** [comment]
@samajammin just updated the project's wiki. Please check it out and let me know if it is sufficient enough for now and we can close this issue for now

**Comment by samajammin** [comment]
Thanks @javier-tarazaga! These look great.

One thing I noticed that I think is worth updating before closing this out:
https://github.com/SuperblocksHQ/ethereum-studio/wiki/Submitting-Bugs-and-Suggestions

> The Ethereum Studio project is distributed across multiple repositories, try to file the issue against the correct repository Related Projects.

"Related Projects" is a dead link:
https://github.com/SuperblocksHQ/ethereum-studio/wiki/Related-Projects

Could you please re-add this page or add links to the related projects?

**Comment by javier-tarazaga** [comment]
@samajammin I updated the text. Now it reads like this.

> The Ethereum Studio project is distributed across multiple repositories, which some of them are private for now. Until they are open-sourced, please fill any new issues you might have with either front-end or server applications in this repository.

**Comment by samajammin** [comment]
Looks good to me, thanks! Closing this out.
