### ISSUE TITLE
Display previews of markdown files

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#34]
## Summary

Display markdown files in preview mode instead of the raw markdown.

## Motivation

Currently the app displays the raw markdown file, which makes for poor UX: it's hard to read & requires lots of horizontal scrolling:
![Image 2019-10-23 at 9 13 27 AM](https://user-images.githubusercontent.com/8097623/67413332-cbc25480-f575-11e9-87cb-0494f9c7c0fc.png)

It'd be great to display a preview of the markdown file instead, e.g. like how [WebAssembly Studio](https://webassembly.studio) does it:
![Image 2019-10-23 at 9 14 38 AM](https://user-images.githubusercontent.com/8097623/67413408-eeed0400-f575-11e9-8bcf-c7c4e0826ced.png)

WebAssembly Studio is also open source:
https://github.com/wasdk/WebAssemblyStudio
Looks like they also use the Monaco Editor & they mention "[Showdown](https://github.com/showdownjs/showdown) is used to automatically preview .md files."

## Describe alternatives you've considered

None.

**Comment by bashlund** [comment]
Thanks @samajammin for the detailed description and tips about `Showdown`!
