### ISSUE TITLE
Invalid number of arguments error after Deploy

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/ethereum-studio#43]
## Environment/Browser
Live environment

## Description
~Calls from _Interact_ panel used to crash the application. Then, reading back from arrays was not possible in _Interact.~

_Deploy_ results in Invalid number of arguments error.

## Steps to reproduce
1. From _Hello World_ template
2. Change `HelloWorld.sol` to:
```
pragma solidity ^0.5.10;
contract HelloWorld {
    uint256[] public message;
    constructor(uint256[] memory initMessage) public {
        message = initMessage;
    }
}
```

3. Go to _Configure_
4. Change argument type from `value` to `array`
5. Set `array` argument value to `1,2,3`, then _Save_.
6. _Compile_
7. _Deploy_

## Expected result
No errors.

## Actual result
Browser console returns:
```
Error: Invalid number of arguments to Solidity function web3.min.js:1
```

~Note: Even though the "Actual result" is similar to #42, this is being flagged a separate issue as its known to be a distinct type, which could be taking a different route.~

**Comment by Spejbl** [comment]
Unable to reproduce on Live environment

**Comment by filippsen** [comment]
@Spejbl deployment reads 
```
[..]
Contract deployed at address 0x....
Done.
```
but then an error messages appears at the end of that _Deploy_ action (Step 7).

The error only appears on the browser console output.
```
Error: Invalid number of arguments to Solidity function
web3.min.js:1:27450
```

**Comment by filippsen** [comment]
Description updated.

**Comment by filippsen** [comment]
@Spejbl this had to do with the _Steps to Reproduce_ which was based on _Hello World_. The modified contract does not include the `update` function, which causes the _Preview_ window to fire off `HelloWorld.update()` in that situation (_app.js_). That would result in:
```
Uncaught Error: Invalid number of arguments to Solidity function
    at Object.InvalidNumberOfSolidityArgs
```

Verification:
Repeating the same 7 steps, but starting off from _Empty Project_ and renaming the reference code from `HelloWorld` to `MyContract` does not result in that error. Closing the issue.
