### ISSUE TITLE
Copy and paste bug when dealing with the editor

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/ethereum-studio#48]
Initially reported as follows:

1. _Select Template_ -> _Hello World_
2. Press _Create Project_
3. Select any text from _README_
4. Copy the contents with _Ctrl/Cmd+C_
5. Select any line inside the same _README_ file
6. (try to) Paste the contents with _Ctrl/Cmd+V_

More details in request #23

**Comment by Spejbl** [comment]
Unable to reproduce on Live environment.
