### ISSUE TITLE
Race condition while compiling project which user doesn't own

### ISSUE THREAD

**Issue by Spejbl** [SuperblocksHQ/ethereum-studio#49]
## Environment/Browser
Chrome/Firefox - local environment

## Description
When user tries to compile a project which they doesn't own, sometimes it doesn't properly fork (create) a new project and fails on api call.

## Steps to reproduce
1. Create a new project in incognito mode (any browser)
2. Copy paste the url of the project and open it up in normal mode
3. Try to compile project (left button in menu)
4. Compilation will either create a new project (redirects to a new id) or it will silently fail with `PUT - 500` error code in console. (There is possibly some race condition somewhere)

## Expected result
Compilation should redirect user to his own new forked project.

## Actual result
Step 4.1

## Reproducible
50%

**Comment by filippsen** [comment]
Following the _Steps to reproduce_ running separate browsers instead consistently results in the reported error.

_Output_ reads:
```
Using Solidity compiler version 0.5.10
Success in compilation
```
