### ISSUE TITLE
OG image preview caching issue

### ISSUE THREAD

**Issue by samajammin** [SuperblocksHQ/ethereum-studio#76]
## Environment/Browser
N/A

## Description
Seems Telegram (& potentiall other platforms) have cached the preview image:
<img width="491" alt="Image 2019-11-04 at 8 44 35 AM" src="https://user-images.githubusercontent.com/8097623/68139653-5cd2ed00-fedf-11e9-9e37-85a24e78909e.png">

We should change the filename & reference.

## Steps to reproduce
Share https://studio.ethereum.org/

## Expected result
Should display new image

## Actual result
Displays old image

## Reproducible
100% (at least in Telegram)

**Comment by javier-tarazaga** [comment]
This should already be fixed and in prod.
