### ISSUE TITLE
Unable to save project which is too large

### ISSUE THREAD

**Issue by Spejbl** [SuperblocksHQ/ethereum-studio#85]
## Environment/Browser
Production/Firefox-Chrome

## Description
When the project is too big, the server doesn't handle the request so it's unable to save such project.

## Steps to reproduce
1. Create CryptoPizza project
2. Compile and Deploy to browser network (this step is important so the build folder gets big enough)
3. Try to modify any file and hit save button
4. Browser's console logs out `500 - Internal server error`

![image (1)](https://user-images.githubusercontent.com/17637244/68203412-4ec4bf80-fff8-11e9-8f44-ebac9605fe64.png)
`{message: request entity too large}`

## Expected result
Should save the project

## Actual result
Doesn't save

## Reproducible
100%

**Comment by ostap1010** [comment]
Fixed
