### ISSUE TITLE
Unable to rename account

### ISSUE THREAD

**Issue by Spejbl** [SuperblocksHQ/ethereum-studio#92]
## Environment/Browser
Live

## Description
When trying to update name of the account, it doesn't update the state in the dropdown, and when trying to rename the "renamed" account again, it crashes application. Although it does correctly update in dappfile.sjon

## Steps to reproduce
1. Create a _New Account_ from topbar dropdown (_Select an Account_)
2. Try to rename newly created `Account1` to `Patata`
3. Observe that it didn't update the name of the account
4. Try to rename the `Account1` once again to `Patata`
5. Whole application crashes with `TypeError: dappFileAccount is undefined`

## Expected result
Account should be renamed

## Actual result
Account doesn't get renamed and it crashes application if trying to rename it again.

Live environment, browser console output returns:
```
TypeError: i is undefined updateAccountName.epic.ts:59:12
```

## Reproducible
100%

**Comment by filippsen** [comment]
Confirmed. 
_Step 3_ leads to no change.
_Step 4_ leads to a broken state which prevents some actions from being called (silent failure)
Error only appears on browser console output. See updated _Actual result_.

**Comment by javier-tarazaga** [comment]
This has to do with some of the changes done in the account managing. Atm the project.reducer is not actually listening to account name changes, therefore not updating the UI in the process.

**Comment by filippsen** [comment]
Possibly related: _Default_ account rename only updates after _New Account_ gets created.
To be confirmed with request #126.
